naam = (input("Wat is je naam?:"))
adres = input("Wat is je adres?:")
postcode = input("Wat is je postcode?:")
woonplaats = input("Wat is je woonplaats?:")

print("----------------------------------------------------")
print("|  Naam      : ", naam ,"                             ")
print("|  Adres     : ", adres ,"                            ")
print("|  Postcode  : ", postcode ,"                         ")
print("|  Woonplaats: ", woonplaats ,"                       ")
print("----------------------------------------------------")